---
- name: Patch all non-jump Debian hosts first
  hosts: all:!jump_hosts
  become: true
  gather_facts: false
  serial: "{{ patch_serial | default('100%') }}"

  vars:
    apt_lock_timeout: 600
    reboot_timeout: 1800

    service_restart_denylist:
      - ssh.service
      - sshd.service
      - dbus.service
      - systemd-logind.service
      - networking.service
      - NetworkManager.service
      - systemd-resolved.service
      - systemd-networkd.service

  tasks:
    - name: Run Debian update workflow
      ansible.builtin.import_tasks: debian-update-host.yml


- name: Patch jump hosts last
  hosts: jump_hosts
  become: true
  gather_facts: false
  serial: 1

  vars:
    apt_lock_timeout: 600
    reboot_timeout: 1800

    service_restart_denylist:
      - ssh.service
      - sshd.service
      - dbus.service
      - systemd-logind.service
      - networking.service
      - NetworkManager.service
      - systemd-resolved.service
      - systemd-networkd.service

  tasks:
    - name: Run Debian update workflow for jump hosts
      ansible.builtin.import_tasks: debian-update-host.yml
