---
###########################################################################
# Phase 1
# Normal Linux servers
###########################################################################

- name: Patch normal Debian hosts first
  hosts: all:!jump_hosts:!hypervisors
  become: true
  gather_facts: false
  serial: "{{ patch_serial | default('100%') }}"

  vars:
    apt_lock_timeout: 600
    reboot_timeout: 1800

  tasks:
    - import_tasks: debian-update-host.yml

###########################################################################
# Phase 2
# Hypervisors
###########################################################################

- name: Patch hypervisors second
  hosts: hypervisors
  become: true
  gather_facts: false
  serial: 1

  vars:
    apt_lock_timeout: 600
    reboot_timeout: 1800

  tasks:
    - import_tasks: debian-update-host.yml

###########################################################################
# Phase 3
# Jump hosts
###########################################################################

- name: Patch jump hosts last
  hosts: jump_hosts
  become: true
  gather_facts: false
  serial: 1

  vars:
    apt_lock_timeout: 600
    reboot_timeout: 1800

  tasks:
    - import_tasks: debian-update-host.yml
