- name: Test inventory
  hosts: all
  gather_facts: false

  tasks:

    - name: Get FQDN
      command: hostname -f
      register: hostname_result

    - name: Print hostname
      debug:
        msg: "Ik ben {{ hostname_result.stdout }}"
